### ISSUE TITLE
First version

### ISSUE THREAD

**Issue by Halama** [keboola/gmail-extractor#1]
Gmail extraktor by měl stahovat emaily přes API gmailu, emaily se budou filtrovat podle query kterou uživatel zadá do konfigurace. U zpráv nás bude zajímát obsah a hlavičky, mohlo by být konfigurovatelné které hlavičky a části těla by to mělo ukládat.

Od Padáka:
Metodou "list" (https://developers.google.com/gmail/api/v1/reference/users/messages/list) bych umožnil vypsat Id zpráv co vyhovují konkrétnímu labelu (labelIds) a nebo zadané query (q). Takže bys do cfg buď vybral label = "linkedin" a ono by ti to tahalo emaily co mají tenhle label a nebo bys tam dal že query = "from:(dan@multimedia.cz) -in:chats smaller:1M after:2005/7/6 before:2006/7/6 larger:10K"

Konkrétní email IDs z odpovědi z "list" resource pak bere get (https://developers.google.com/gmail/api/v1/reference/users/messages/get) - tady jde taky testovat API call, pres ui se autorizuješ, zadáš tam do userId=me a do id=idEmailu (najdeš v gmailu - koukám na email a v url je https://mail.google.com/mail/u/0/#inbox/1531a3235c7cf136 tak pak je id zprávy 1531a3235c7cf136) - vrátí to jak vypadá request:

GET https://www.googleapis.com/gmail/v1/users/me/messages/1531a3235c7cf136?key={YOUR_API_KEY}

a pak jak vypadá odpověď (https://gist.github.com/padak/4ce82f5a337b43f74854), kde text emailu je encodnutej do base64.

Kdybysme to chtěli udělat pořádně, tak bych nechal pro gmail cfg nastavit, co nás zajímá z hlaviček (Date, From, To, Subject,... - viz gist od ř. 26) a co z body/data (od č. 128) kde je možnost vzít text/plain a/nebo text/html result.

## Implementace
Extraktor bude naimplementován jako Docker komponenta do Keboola Connection podle http://wiki.keboola.com/home/keboola-connection/devel-space/developing-docker-app

Pro inspiraci se můžou hodit už hotové extraktory:
- adwords https://github.com/keboola/adwords-extractor - integruje s Keboola Oauth komponentou https://github.com/keboola/oauth-v2-bundle což bude hádám pro Gmail stejné  
- firebird https://github.com/keboola/db-extractor-firebird

Konfigurace extraktoru by mohla vypadat zhruba takhle:
```
{
    "parameters": {
        "queries": [
            {
                "name": "todo",
                "query": "label:todo" 
            }
        ]
    },
    "authorization": {
        "oauth_api": {
            "id": "xxx"
        }
    }
}
```

Feature: https://keboola.productboard.com/release-board/planning/features/38037

**Comment by Halama** [comment]
Integrace oauth https://www.evernote.com/shard/s4/sh/709dd2e0-3cc0-4b3a-8d71-5da43dde1997/f8ee69d7cab1957b

**Comment by ujovlado** [comment]
Prva verzia je tam.

Config zatial vyzera takto:
```yaml
parameters:
  q: 'from:vlado@keboola.com'
authorization:
  oauth_api:
    credentials:
      '#data': "YOUR_AWESOME_JSON"
image_parameters:
  '#client_id': 'CLIENT_ID'
  '#client_secret': 'CLIENT_SECRET'
```
Par detailov:
- vystupom su subory: `messages.csv`, `headers.csv` a `parts.csv` (+ ku kazdemu `.manifest`)
- parameter `q` je povinny, aby sme by default nestahovali cely inbox ale vzdy len query (ak si ju user naspecifikuje tak, ze to bude cely inbox, je to jeho vec :wink: )
- este pribudne to stahovannie len konkretnych headers
- `labelIds` to zatial nepodporuje, je tam mala issue, su to totiz gmailovske IDcka tych labelov (napr. `Label_44`)
- testy pridam :innocent:

**Comment by Halama** [comment]
jeste by pak asi bylo fajn kdyby ta jedna konfigurace mohla obsahovat více queries. Bude to jednotnější se zbytkem extraktrorů. Konfigurace typu:
```
 "queries": [
            {
                "name": "todo",
                "query": "label:todo" 
            }
        ]
```

jméno query by to pak mohlo přidat do tabulky se zprávami.
