### ISSUE TITLE
Progress during extraction

### ISSUE THREAD

**Issue by ujovlado** [keboola/gmail-extractor#2]
Bolo by fajn vidiet progress pocas fetchovania emailov, napr. "Downloading page 1 of XX"

**Comment by ujovlado** [comment]
Takto to dava:
```
root@0a2bff1da609:/code# php src/run.php --data=/data
Queries: 2
Processing query: to:some.address@example.com
Processed results: 100
Processed results: 200
Processed results: 300
Processed results: 340
Done.
Processing query: from:newsletters-no-reply@myfonts.com OR from:notifications@github.com
Processed results: 100
Processed results: 139
Done.
```

**Comment by Halama** [comment]
to vypada dobre. Nevraci to na zacatku i kolik toho bude celkem?
Ze by to ukazoval treba `Processed results: 100 / 950` ...

**Comment by ujovlado** [comment]
@Halama ano, tak som to chcel, no `getResultSizeEstimate` vracia nezmysly (resp. vyzera to skor na priblizny pocet pre aktualnu stranku). Tuna som napr. stahoval 410 emailov a zakazdym som volal tu funkciu.

```
Estimate size: 103
Estimate size: 103
Estimate size: 103
Estimate size: 103
Estimate size: 10
```

**Comment by ujovlado** [comment]
Nehal by som to zatial takto a potom skusim upgradnut na novsiu verziu ich client library, ci to nefixli.

**Comment by Halama** [comment]
jo v pohode. imho to takhle vraci to jejich API, stejne se tusim chova google vyhledavani. Tak bych to asi neresil
